-- DROP SCHEMA public;

CREATE SCHEMA public AUTHORIZATION pg_database_owner;

-- DROP SEQUENCE public.avion_id_avion_seq;

CREATE SEQUENCE public.avion_id_avion_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.modele_id_modele_seq;

CREATE SEQUENCE public.modele_id_modele_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.reservation_fille_id_reservation_fille_seq;

CREATE SEQUENCE public.reservation_fille_id_reservation_fille_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.reservation_id_reservation_seq;

CREATE SEQUENCE public.reservation_id_reservation_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.siege_modele_id_siege_modele_seq;

CREATE SEQUENCE public.siege_modele_id_siege_modele_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.type_siege_id_type_siege_seq;

CREATE SEQUENCE public.type_siege_id_type_siege_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.utilisateur_id_utilisateur_seq;

CREATE SEQUENCE public.utilisateur_id_utilisateur_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.ville_id_ville_seq;

CREATE SEQUENCE public.ville_id_ville_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.vol_id_vol_seq;

CREATE SEQUENCE public.vol_id_vol_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;-- public.modele definition

-- Drop table

-- DROP TABLE public.modele;

CREATE TABLE public.modele (
	id_modele int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	libelle varchar(255) NULL,
	CONSTRAINT modele_pkey PRIMARY KEY (id_modele)
);


-- public.type_siege definition

-- Drop table

-- DROP TABLE public.type_siege;

CREATE TABLE public.type_siege (
	id_type_siege int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	libelle varchar(255) NULL,
	CONSTRAINT type_siege_pkey PRIMARY KEY (id_type_siege)
);


-- public.utilisateur definition

-- Drop table

-- DROP TABLE public.utilisateur;

CREATE TABLE public.utilisateur (
	id_utilisateur int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	email varchar(255) NULL,
	mot_de_passe varchar(255) NULL,
	nom varchar(255) NULL,
	statut int4 NOT NULL,
	CONSTRAINT utilisateur_pkey PRIMARY KEY (id_utilisateur)
);


-- public.ville definition

-- Drop table

-- DROP TABLE public.ville;

CREATE TABLE public.ville (
	id_ville int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	nom varchar(255) NULL,
	CONSTRAINT ville_pkey PRIMARY KEY (id_ville)
);


-- public.avion definition

-- Drop table

-- DROP TABLE public.avion;

CREATE TABLE public.avion (
	id_avion int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	date_fabrication date NULL,
	libelle varchar(255) NULL,
	id_modele int4 NULL,
	CONSTRAINT avion_pkey PRIMARY KEY (id_avion),
	CONSTRAINT fkkfcha04h7klbb95fqyc5mghcl FOREIGN KEY (id_modele) REFERENCES public.modele(id_modele)
);


-- public.siege_modele definition

-- Drop table

-- DROP TABLE public.siege_modele;

CREATE TABLE public.siege_modele (
	id_siege_modele int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	nb_siege int4 NULL,
	id_modele int4 NULL,
	id_type_siege int4 NULL,
	CONSTRAINT siege_modele_pkey PRIMARY KEY (id_siege_modele),
	CONSTRAINT fk4hhl8ivhpq5uy5rjtfqn9px9k FOREIGN KEY (id_modele) REFERENCES public.modele(id_modele),
	CONSTRAINT fkfrybjhsmk388pvj8t585awwc FOREIGN KEY (id_type_siege) REFERENCES public.type_siege(id_type_siege)
);


-- public.vol definition

-- Drop table

-- DROP TABLE public.vol;

CREATE TABLE public.vol (
	id_vol int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	date_arrivee timestamp(6) NOT NULL,
	date_depart timestamp(6) NOT NULL,
	prix_base numeric(12, 2) NOT NULL,
	id_avion int4 NOT NULL,
	ville_arrivee int4 NOT NULL,
	ville_depart int4 NOT NULL,
	CONSTRAINT vol_pkey PRIMARY KEY (id_vol),
	CONSTRAINT fk8f1ehb8k2sv98y3ju7agkc3rm FOREIGN KEY (id_avion) REFERENCES public.avion(id_avion),
	CONSTRAINT fkmg6kgt2colbsjs49pi7oogwwu FOREIGN KEY (ville_depart) REFERENCES public.ville(id_ville),
	CONSTRAINT fksatuyjf99pc7w7ur5tf7a8ngc FOREIGN KEY (ville_arrivee) REFERENCES public.ville(id_ville)
);


-- public.reservation definition

-- Drop table

-- DROP TABLE public.reservation;

CREATE TABLE public.reservation (
	id_reservation int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	date_reservation timestamp(6) NULL,
	id_utilisateur int4 NOT NULL,
	id_vol int4 NOT NULL,
	CONSTRAINT reservation_pkey PRIMARY KEY (id_reservation),
	CONSTRAINT fk3kt9mawec4sqdm8j6830e8yp9 FOREIGN KEY (id_utilisateur) REFERENCES public.utilisateur(id_utilisateur),
	CONSTRAINT fk6w89wb2jeg31kddarxq85d66o FOREIGN KEY (id_vol) REFERENCES public.vol(id_vol)
);


-- public.reservation_fille definition

-- Drop table

-- DROP TABLE public.reservation_fille;

CREATE TABLE public.reservation_fille (
	id_reservation_fille int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	numero_siege varchar(255) NOT NULL,
	prix numeric(12, 2) NOT NULL,
	id_reservation int4 NOT NULL,
	id_type_siege int4 NOT NULL,
	CONSTRAINT reservation_fille_pkey PRIMARY KEY (id_reservation_fille),
	CONSTRAINT fk2pocq901cc76btv5gmp634fox FOREIGN KEY (id_reservation) REFERENCES public.reservation(id_reservation),
	CONSTRAINT fkfic479b4ko2alwjmopyamhrti FOREIGN KEY (id_type_siege) REFERENCES public.type_siege(id_type_siege)
);